name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    runs-on: windows-2019
    name: ${{ matrix.platform.str }}-${{ matrix.cfg.str }}
    strategy:
      matrix:
        platform:
          - { generator: Visual Studio 16 2019, arch: Win32, qt-arch: win32_msvc2019, str: windows-x86 }
          - { generator: Visual Studio 16 2019, arch: x64, qt-arch: win64_msvc2019_64, str: windows-x64 }
        cfg:
          - { external: OFF, type: RelWithPDB, str: internal-release }
          - { external: OFF, type: Debug, str: internal-debug }
          - { external: ON, type: RelWithPDB, str: external-release }

    steps:
      - name: Checkout Plasma
        uses: actions/checkout@v3

      - name: Setup NuGet
        run: |
          nuget sources add `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" `
              -storepasswordincleartext `
              -name "GitHub" `
              -username "${{ github.repository_owner }}" `
              -password "${{ secrets.GITHUB_TOKEN }}"

          nuget setapikey `
              "${{ secrets.GITHUB_TOKEN }}" `
              -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Configure
        run: |
          cmake `
            -G "${{ matrix.platform.generator }}" -A "${{ matrix.platform.arch }}" `
            -DPLASMA_BUILD_LAUNCHER=OFF `
            -DPLASMA_BUILD_TESTS=ON `
            -DPLASMA_EXTERNAL_RELEASE=${{ matrix.cfg.external }} `
            -DVCPKG_INSTALL_OPTIONS=--clean-after-build `
            -S . -B build
        env:
          VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,readwrite"

      - name: Build
        run: |
          cmake --build build --config "${{ matrix.cfg.type }}" -j 2

      - name: Install
        run: |
          cmake --build build --target INSTALL --config "${{ matrix.cfg.type }}" -j 2

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plasma-${{ matrix.platform.str }}-${{ matrix.cfg.str }}
          path: build/install

      - name: Test
        run: |
          cmake --build build --target check --config "${{ matrix.cfg.type }}" -j 2
